-- SELECT id, name, datetime(birthday, 'unixepoch'), birthday FROM OFFICERS
-- insert into officers(name, birthday) values ('Nguyen Minh Anh', unixepoch('1989-04-01', 'localtime'))
-- SELECT *, date(created_at, 'unixepoch', 'localtime') as created_at FROM profiles
-- select datetime(unixepoch(), 'unixepoch', 'localtime'), unixepoch(), unixepoch('subsec'), current_timestamp;
-- select datetime(unixepoch('2024-01-10 00:12:00', 'utc'), 'unixepoch', 'localtime')
-- select unixepoch('1989-04-01', 'localtime')
INSERT INTO places(name, type, code) values ('Quy Nhơn, Bình Định','BDIQN','Thành phố');
INSERT INTO places(name, type, code) values ('An Nhơn, Bình Định','BDIAN','Thị xã');
INSERT INTO places(name, type, code) values ('Hoài Nhơn, Bình Định','BDIHN','Thị xã');
INSERT INTO places(name, type, code) values ('An Lão, Bình Định','BDIAL','Huyện');
INSERT INTO places(name, type, code) values ('Hoài Ân, Bình Định','BDIHA','Huyện');
INSERT INTO places(name, type, code) values ('Phù Cát, Bình Định','BDIPC','Huyện');
INSERT INTO places(name, type, code) values ('Phù Mỹ, Bình Định','BDIPM','Huyện');
INSERT INTO places(name, type, code) values ('Tây Sơn, Bình Định','BDITS','Huyện');
INSERT INTO places(name, type, code) values ('Tuy Phước, Bình Định','BDITP','Huyện');
INSERT INTO places(name, type, code) values ('Vân Canh, Bình Định','BDIVC','Huyện');
INSERT INTO places(name, type, code) values ('Vĩnh Thạnh, Bình Định','BDITT','Huyện');
INSERT INTO places(name, type, code) values ('Hà Nội','HNO','Thành phố');
INSERT INTO places(name, type, code) values ('TP Hồ Chí Minh','HCM','Thành phố');
INSERT INTO places(name, type, code) values ('Hà Giang','HGI','Tỉnh');
INSERT INTO places(name, type, code) values ('Cao Bằng','CBA','Tỉnh');
INSERT INTO places(name, type, code) values ('Lào Cai','LCI','Tỉnh');
INSERT INTO places(name, type, code) values ('Sơn La','SLA','Tỉnh');
INSERT INTO places(name, type, code) values ('Lai Châu','LCA','Tỉnh');
INSERT INTO places(name, type, code) values ('Bắc Kạn','BKA','Tỉnh');
INSERT INTO places(name, type, code) values ('Lạng Sơn','LSN','Tỉnh');
INSERT INTO places(name, type, code) values ('Tuyên Quang','TQU','Tỉnh');
INSERT INTO places(name, type, code) values ('Yên Bái','YBA','Tỉnh');
INSERT INTO places(name, type, code) values ('Thái Nguyên','TNG','Tỉnh');
INSERT INTO places(name, type, code) values ('Điện Biên','DBI','Tỉnh');
INSERT INTO places(name, type, code) values ('Phú Thọ','PTH','Tỉnh');
INSERT INTO places(name, type, code) values ('Vĩnh Phúc','VPH','Tỉnh');
INSERT INTO places(name, type, code) values ('Bắc Giang','BGI','Tỉnh');
INSERT INTO places(name, type, code) values ('Bắc Ninh','BNI','Tỉnh');
INSERT INTO places(name, type, code) values ('Quảng Ninh','QNH','Tỉnh');
INSERT INTO places(name, type, code) values ('Hải Dương','HDU','Tỉnh');
INSERT INTO places(name, type, code) values ('Hải Phòng','HPG','Thành phố');
INSERT INTO places(name, type, code) values ('Hòa Bình','HBI','Tỉnh');
INSERT INTO places(name, type, code) values ('Hưng Yên','HYE','Tỉnh');
INSERT INTO places(name, type, code) values ('Hà Nam','HNA','Tỉnh');
INSERT INTO places(name, type, code) values ('Thái Bình','TBH','Tỉnh');
INSERT INTO places(name, type, code) values ('Nam Định','NDH','Tỉnh');
INSERT INTO places(name, type, code) values ('Ninh Bình','NBI','Tỉnh');
INSERT INTO places(name, type, code) values ('Thanh Hóa','THA','Tỉnh');
INSERT INTO places(name, type, code) values ('Nghệ An','NAN','Tỉnh');
INSERT INTO places(name, type, code) values ('Hà Tĩnh','HTI','Tỉnh');
INSERT INTO places(name, type, code) values ('Quảng Bình','QBI','Tỉnh');
INSERT INTO places(name, type, code) values ('Quảng Trị','QTR','Tỉnh');
INSERT INTO places(name, type, code) values ('Thừa Thiên Huế','TTH','Tỉnh');
INSERT INTO places(name, type, code) values ('Đà Nẵng','DNG','Thành phố');
INSERT INTO places(name, type, code) values ('Quảng Nam','QNA','Tỉnh');
INSERT INTO places(name, type, code) values ('Quảng Ngãi','QNG','Tỉnh');
INSERT INTO places(name, type, code) values ('Kon Tum','KTU','Tỉnh');
INSERT INTO places(name, type, code) values ('Gia Lai','GLA','Tỉnh');
INSERT INTO places(name, type, code) values ('Phú Yên','PYE','Tỉnh');
INSERT INTO places(name, type, code) values ('Đắk Lắk','DLA','Tỉnh');
INSERT INTO places(name, type, code) values ('Khánh Hòa','KHA','Tỉnh');
INSERT INTO places(name, type, code) values ('Đắk Nông','DKN','Tỉnh');
INSERT INTO places(name, type, code) values ('Lâm Đồng','LDG','Tỉnh');
INSERT INTO places(name, type, code) values ('Ninh Thuận','NTH','Tỉnh');
INSERT INTO places(name, type, code) values ('Bình Phước','BPC','Tỉnh');
INSERT INTO places(name, type, code) values ('Tây Ninh','TNI','Tỉnh');
INSERT INTO places(name, type, code) values ('Bình Dương','BDU','Tỉnh');
INSERT INTO places(name, type, code) values ('Đồng Nai','DNA','Tỉnh');
INSERT INTO places(name, type, code) values ('Bình Thuận','BTN','Tỉnh');
INSERT INTO places(name, type, code) values ('Long An','LAN','Tỉnh');
INSERT INTO places(name, type, code) values ('Bà Rịa – Vũng Tàu','VTB','Tỉnh');
INSERT INTO places(name, type, code) values ('Đồng Tháp','DTP','Tỉnh');
INSERT INTO places(name, type, code) values ('An Giang','AGI','Tỉnh');
INSERT INTO places(name, type, code) values ('Tiền Giang','TGG','Tỉnh');
INSERT INTO places(name, type, code) values ('Vĩnh Long','VLG','Tỉnh');
INSERT INTO places(name, type, code) values ('Bến Tre','BTR','Tỉnh');
INSERT INTO places(name, type, code) values ('Cần Thơ','CTH','Thành phố');
INSERT INTO places(name, type, code) values ('Kiên Giang','KGI','Tỉnh');
INSERT INTO places(name, type, code) values ('Trà Vinh','TVH','Tỉnh');
INSERT INTO places(name, type, code) values ('Hậu Giang','HAG','Tỉnh');
INSERT INTO places(name, type, code) values ('Sóc Trăng','STR','Tỉnh');
INSERT INTO places(name, type, code) values ('Bạc Liêu','BLI','Tỉnh');
INSERT INTO places(name, type, code) values ('Cà Mau','CMU','Tỉnh');

